


stages:
- build
- deploy

build:
  image: maven:latest
  stage: build
  script:
    - mvn clean compile assembly:single
  artifacts:
    paths:
      - ./target

deploy:
  image: lgatica/openssh-client
  stage: deploy
  before_script:
    - mkdir $HOME/.ssh
    - chmod 700 $HOME/.ssh
    - echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_ecdsa
    - chmod 600 $HOME/.ssh/id_ecdsa
    - cat $HOME/.ssh/id_ecdsa

  after_script:
    - rm -rf $HOME/.ssh
  dependencies:
    - build
  script:
    - cd target
    - echo $PWD; ls -l
    - scp -o StrictHostKeyChecking=no -i $HOME/.ssh/id_ecdsa Template-0.0.3-jar-with-dependencies.jar mazerunner@www.se-challenge.nl:games/$CI_PROJECT_NAME.jar
